<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.jenkins-ci.plugins</groupId>
        <artifactId>plugin</artifactId>
        <version>6.2211.v27f680c93c53</version>
        <relativePath/>
    </parent>
    <groupId>io.jenkins.plugins</groupId>
    <artifactId>harness</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>hpi</packaging>
    <name>Harness Plugin</name>
    <description>A plugin to integrate harness artifact registry CLI with Jenkins</description>
    <url>https://github.com/jenkinsci/${project.artifactId}-plugin</url>

    <properties>
        <jenkins.baseline>2.541</jenkins.baseline>
        <jenkins.version>${jenkins.baseline}.3</jenkins.version>
        <hpi.strictBundledArtifacts>true</hpi.strictBundledArtifacts>
        <banObsoleteDependencyOverrides.skip>false</banObsoleteDependencyOverrides.skip>
        <ban-junit4-imports.skip>false</ban-junit4-imports.skip>
        <ban-deprecated-stapler.skip>false</ban-deprecated-stapler.skip>
        <ban-commons-lang-2.skip>false</ban-commons-lang-2.skip>
    </properties>


    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <organization>
        <name>Harness</name>
        <url>https://harness.io</url>
    </organization>

    <scm>
        <connection>scm:git:https://github.com/jenkinsci/${project.artifactId}-plugin.git</connection>
        <developerConnection>scm:git:https://github.com/jenkinsci/${project.artifactId}-plugin.git</developerConnection>
        <url>https://github.com/jenkinsci/${project.artifactId}-plugin</url>
        <tag>${scmTag}</tag>
    </scm>
    <repositories>
        <repository>
            <id>repo.jenkins-ci.org</id>
            <url>https://repo.jenkins-ci.org/public/</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>repo.jenkins-ci.org</id>
            <url>https://repo.jenkins-ci.org/public/</url>
        </pluginRepository>
    </pluginRepositories>

    <dependencies>
        <dependency>
            <groupId>org.jenkins-ci.plugins.workflow</groupId>
            <artifactId>workflow-step-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jenkins-ci.plugins.workflow</groupId>
            <artifactId>workflow-cps</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jenkinsci.plugins</groupId>
            <artifactId>pipeline-model-definition</artifactId>
        </dependency>
        <dependency>
            <groupId>io.jenkins.plugins</groupId>
            <artifactId>commons-lang3-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.jenkins</groupId>
            <artifactId>configuration-as-code</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.jenkins.tools.bom</groupId>
                <artifactId>bom-2.541.x</artifactId>
                <version>7002.v028a_3607ddc8</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
